name: Build
on:
  push: ~
  pull_request: ~

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: make build
        shell: bash
